"""changes data type in appliance table

Revision ID: 220b1a3a1310
Revises: ec79d12405a8
Create Date: 2018-06-25 10:59:24.515879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220b1a3a1310'
down_revision = 'ec79d12405a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
