"""adds index to sample table

Revision ID: 326a9a34f052
Revises: 75f13e7785b5
Create Date: 2018-07-04 12:43:26.287315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326a9a34f052'
down_revision = '75f13e7785b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sample_power_source_id_timestamp_physical_quantity_id_idx', 'sample', ['power_source_id', 'timestamp', 'physical_quantity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sample_power_source_id_timestamp_physical_quantity_id_idx', table_name='sample')
    # ### end Alembic commands ###
