"""Adds new columns to appliance_type

Revision ID: 75f13e7785b5
Revises: 220b1a3a1310
Create Date: 2018-07-04 12:15:30.570668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f13e7785b5'
down_revision = '220b1a3a1310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliance_type', sa.Column('max_power', sa.REAL(), nullable=True))
    op.add_column('appliance_type', sa.Column('min_off_duration', sa.REAL(), nullable=True))
    op.add_column('appliance_type', sa.Column('min_on_duration', sa.REAL(), nullable=True))
    op.add_column('appliance_type', sa.Column('on_power_threshold', sa.REAL(), nullable=True))
    op.drop_index('sample_power_source_id_timestamp_physical_quantity_id_idx', table_name='sample')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sample_power_source_id_timestamp_physical_quantity_id_idx', 'sample', ['power_source_id', 'timestamp', 'physical_quantity_id'], unique=False)
    op.drop_column('appliance_type', 'on_power_threshold')
    op.drop_column('appliance_type', 'min_on_duration')
    op.drop_column('appliance_type', 'min_off_duration')
    op.drop_column('appliance_type', 'max_power')
    # ### end Alembic commands ###
