"""removes description column from aggregate model, it was duplicate

Revision ID: b79cbeffedcf
Revises: c1b64c32701a
Create Date: 2018-06-20 16:39:17.013233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79cbeffedcf'
down_revision = 'c1b64c32701a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregate', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregate', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
