"""adds some columns to aggregate and sample models

Revision ID: c1b64c32701a
Revises: d3b555e2974c
Create Date: 2018-06-20 14:46:57.449131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b64c32701a'
down_revision = 'd3b555e2974c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregate', sa.Column('description', sa.TEXT(), nullable=False))
    op.add_column('sample', sa.Column('is_on', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'is_on')
    op.drop_column('aggregate', 'description')
    # ### end Alembic commands ###
