"""empty message

Revision ID: c58c0a898df8
Revises: b79cbeffedcf
Create Date: 2018-06-21 12:21:28.478344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58c0a898df8'
down_revision = 'b79cbeffedcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_source', sa.Column('location', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('power_source', 'location')
    # ### end Alembic commands ###
