"""adds sampling_period columns to power_sources

Revision ID: e810bd8347c9
Revises: 326a9a34f052
Create Date: 2018-07-12 10:46:35.714530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e810bd8347c9'
down_revision = '326a9a34f052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_source', sa.Column('sampling_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('power_source', 'sampling_period')
    # ### end Alembic commands ###
