"""changes data type in appliance table

Revision ID: ec79d12405a8
Revises: c58c0a898df8
Create Date: 2018-06-25 10:31:56.997390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec79d12405a8'
down_revision = 'c58c0a898df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
